# Use root/example as user/password credentials
version: '3.1'

services:

    app:
        container_name: gorillaMongo
        build: .
        ports: 
            -8080:8080
        restart: on-failure
        environment: 
            PORT: 27017
            DB_CONN: "mongodb://127.0.0.1:27017/?readPreference=primary&appname=mongodb-vscode%200.5.0&ssl=false"
        